### PR TITLE
Trim helper

### PR DESCRIPTION
**Pull request by r0qs**
This helper trim a string by removing leading and trailing whitespace or specified characters.

### CODE REVIEW

**Comment by luizsignorelli** [comment]
looks good 👍

**Comment by r0qs** [comment]
@luizsignorelli, aprova? Posso mandar pra qa pra testar? :D

**Comment by danilobuiatti** [comment]
zupbot ready-for-qa

**Comment by r0qs** [comment]
zupbot ready-for-qa

**Pull request merged**
